---

language: node_js
node_js:
  - node
addons:
    code_climate:
        repo_token: e4c29073c72ef50b99678c8f643169e1d55120f537467dc74eabafca048f1760

before_script:
  - npm install --save-dev codeclimate-test-reporter

script:
  - make lint
  - make test

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
